#!/usr/bin/env python
class Movie:
    def __init__(self, name, year, price):
        self.name = name
        self.year = year
        self.price = price

    def getStr(self):
        return f"{self.name} ({self.year}) ({self.price})"

def list_movies(movie_list):
    if len(movie_list) == 0:
        print("There are no movies in the list.\n")
    else:
        for i, movie in enumerate(movie_list, start=1):
            print(str(i) + ", " + movie.getStr())
        print()

def add_movie(movie_list):
    name = input("Name: ")
    year = input("Year: ")
    price = input("Price: ")
    movie = Movie(name, year, price)
    movie_list.append(movie)
    print(movie.name + " was added.\n")

def delete_movie(movie_list):
    number = int(input("Number: "))
    if number < 1 or number > len(movie_list):
        print("Invalid movie number.\n")
    else:
        movie = movie_list.pop(number-1)
        print(movie.name + " was deleted.\n")

def display_menu():
    print("COMMAND MENU")
    print("list - List all movies")
    print("add - Add a movie")
    print("del - Delete a movie")
    print("exit - Exit program")
    print()

def main():
    userInput = input("Please enter your name: ")
    movie_list = [
        Movie("Monty Python and the Holy Grail", 1975, 12.95),
        Movie("Castaway", 2000, 12.95),
        Movie("On the Waterfront", 1954, 9.95),
        Movie("Night of the living Dead", 1968, 7.95),
        Movie("Cat on a Hot Tin Roof", 1958, 7.95),
        Movie("Long Hot Summer",1958, 9.95)
    ]

    display_menu()

    while True:
        command = input("Command: ")
        if command == "list":
            list_movies(movie_list)
        elif command == "add":
            add_movie(movie_list)
        elif command == "del":
            delete_movie(movie_list)
        elif command == "exit":
            break
        else:
            print("Not a valid command. Please try again.\n")

    print("Goodbye!")
